In [3]:
import numpy as np
#for numpy import array

In [4]:
s=np.array([1,2,3,])
s

array([1, 2, 3])

In [4]:
np.array([1,2,3,4,5.5])


array([1. , 2. , 3. , 4. , 5.5])

In [5]:
a1=np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [7]:
type(a3)

numpy.ndarray

In [8]:
a3.ndim

3

In [9]:
a3.dtype

dtype('int32')

In [10]:
a3.size

9

In [11]:
a3.itemsize

4

### METHODS TO CREATE ARRAYS
*RANGE
*ARANGE
*LINSPACE

In [12]:
#range
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#arange
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.array(range(10,1,-2))

array([10,  8,  6,  4,  2])

In [15]:
np.array(range(1,10,2))

array([1, 3, 5, 7, 9])

In [16]:
#linspace
np.array(range(1,10,5))

array([1, 6])

In [17]:
np.logspace(1,10,base = 10)

array([1.00000000e+01, 1.52641797e+01, 2.32995181e+01, 3.55648031e+01,
       5.42867544e+01, 8.28642773e+01, 1.26485522e+02, 1.93069773e+02,
       2.94705170e+02, 4.49843267e+02, 6.86648845e+02, 1.04811313e+03,
       1.59985872e+03, 2.44205309e+03, 3.72759372e+03, 5.68986603e+03,
       8.68511374e+03, 1.32571137e+04, 2.02358965e+04, 3.08884360e+04,
       4.71486636e+04, 7.19685673e+04, 1.09854114e+05, 1.67683294e+05,
       2.55954792e+05, 3.90693994e+05, 5.96362332e+05, 9.10298178e+05,
       1.38949549e+06, 2.12095089e+06, 3.23745754e+06, 4.94171336e+06,
       7.54312006e+06, 1.15139540e+07, 1.75751062e+07, 2.68269580e+07,
       4.09491506e+07, 6.25055193e+07, 9.54095476e+07, 1.45634848e+08,
       2.22299648e+08, 3.39322177e+08, 5.17947468e+08, 7.90604321e+08,
       1.20679264e+09, 1.84206997e+09, 2.81176870e+09, 4.29193426e+09,
       6.55128557e+09, 1.00000000e+10])

In [18]:
import math
math.log2(3)

1.584962500721156

In [19]:
np.random.randint(5,10)

6

In [20]:
np.random.randint(10)

9

In [21]:
a3.shape

(1, 3, 3)

### RANDOM ARRAY CREATIONS
*random.randint
*random.randn
*random.random
*random.rand

In [22]:
np.random.randint(5,10,(3,6))

array([[7, 9, 8, 6, 5, 8],
       [9, 9, 8, 8, 7, 7],
       [5, 9, 9, 8, 7, 5]])

In [23]:
np.random.randn(3,5)

array([[-1.53101597, -0.16227947, -0.10309841, -1.12247608,  0.44822807],
       [ 0.77572909,  0.05000646,  0.10277245,  0.47196809,  0.36665509],
       [ 0.20436458, -0.3159701 , -1.33447235, -0.95083372,  0.05384899]])

In [24]:
np.random.random((3,5))

array([[0.78140603, 0.47192131, 0.90460525, 0.05336537, 0.93422965],
       [0.08755648, 0.18409476, 0.39924517, 0.84338671, 0.28887843],
       [0.53332596, 0.59455587, 0.31882739, 0.28499416, 0.10534956]])

In [25]:
np.random.rand(3,5)

array([[0.68819274, 0.38909036, 0.63476357, 0.69927221, 0.22176802],
       [0.6061275 , 0.25227587, 0.94191559, 0.59313956, 0.4320308 ],
       [0.9940457 , 0.97643241, 0.33338291, 0.31410627, 0.76006119]])

In [26]:
np.random.rand(3,5)

array([[0.20105424, 0.0390942 , 0.04923755, 0.92042874, 0.87633369],
       [0.76609962, 0.12646233, 0.1734476 , 0.20001742, 0.16773763],
       [0.42409125, 0.97589396, 0.52335966, 0.51769478, 0.67977199]])

In [27]:
np.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.full((2,4),5.6)

array([[5.6, 5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6, 5.6]])

In [30]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [31]:
np.diag([4,3,7])

array([[4, 0, 0],
       [0, 3, 0],
       [0, 0, 7]])

In [32]:
np.eye(4,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [33]:
np.eye(4,5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
a=np.random.randint(1,100,(5,5))

In [38]:
a[2:4]

array([[27, 82, 65, 29, 40],
       [92, 59, 31, 93, 79]])

In [39]:
a[2:4,1:4]

array([[82, 65, 29],
       [59, 31, 93]])

In [43]:
a1="A M REDDY"
a1[1:5]

' M R'

In [47]:
S="A M REDDY"

In [48]:
S[1:6:2]

'  E'

In [49]:
S

'A M REDDY'

In [51]:
S[::2]

'AMRDY'

In [8]:
a=np.array([[1,2,3],[3,5,3]])
l=[6,4,7]
b=np.array(l)
b

array([6, 4, 7])

In [11]:
np.hstack(a,b)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [15]:
a=np.arange(1,100)
a.reshape(3,11,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [28, 29, 30],
        [31, 32, 33]],

       [[34, 35, 36],
        [37, 38, 39],
        [40, 41, 42],
        [43, 44, 45],
        [46, 47, 48],
        [49, 50, 51],
        [52, 53, 54],
        [55, 56, 57],
        [58, 59, 60],
        [61, 62, 63],
        [64, 65, 66]],

       [[67, 68, 69],
        [70, 71, 72],
        [73, 74, 75],
        [76, 77, 78],
        [79, 80, 81],
        [82, 83, 84],
        [85, 86, 87],
        [88, 89, 90],
        [91, 92, 93],
        [94, 95, 96],
        [97, 98, 99]]])

In [20]:
a=np.arange(50)
a.size

50

In [24]:
t = a.reshape(10,5)

In [23]:
t.shape[0]

10

In [28]:
a=np.reshape(900)
np.reshape(-1,10)

TypeError: _reshape_dispatcher() missing 1 required positional argument: 'newshape'

In [32]:
a=np.arange(1,900)
a.reshape(30,3,10)

ValueError: cannot reshape array of size 899 into shape (30,3,10)